[package]
name = "jp-importer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
jp-core = { path = "../jp-core" }
encoding_rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
csv = { workspace = true }
